// Tuning presets, strings listed low (thickest) to high.
// Notes use scientific pitch notation: C4 = middle C, A4 = 440 Hz by default.
const INSTRUMENTS = {
  guitar6: {
    name: "Guitar (6-string)",
    strings: 6,
    tunings: [
      { group: "Standard & lowered", name: "Standard", notes: ["E2", "A2", "D3", "G3", "B3", "E4"] },
      { group: "Standard & lowered", name: "Half step down (Eb)", notes: ["Eb2", "Ab2", "Db3", "Gb3", "Bb3", "Eb4"] },
      { group: "Standard & lowered", name: "Full step down (D)", notes: ["D2", "G2", "C3", "F3", "A3", "D4"] },
      { group: "Standard & lowered", name: "C# standard", notes: ["C#2", "F#2", "B2", "E3", "G#3", "C#4"] },
      { group: "Standard & lowered", name: "C standard", notes: ["C2", "F2", "Bb2", "Eb3", "G3", "C4"] },
      { group: "Standard & lowered", name: "B standard", notes: ["B1", "E2", "A2", "D3", "F#3", "B3"] },
      { group: "Drop", name: "Drop D", notes: ["D2", "A2", "D3", "G3", "B3", "E4"] },
      { group: "Drop", name: "Drop C#", notes: ["C#2", "G#2", "C#3", "F#3", "A#3", "D#4"] },
      { group: "Drop", name: "Drop C", notes: ["C2", "G2", "C3", "F3", "A3", "D4"] },
      { group: "Drop", name: "Drop B", notes: ["B1", "F#2", "B2", "E3", "G#3", "C#4"] },
      { group: "Drop", name: "Drop A#", notes: ["A#1", "F2", "A#2", "D#3", "G3", "C4"] },
      { group: "Drop", name: "Drop A", notes: ["A1", "E2", "A2", "D3", "F#3", "B3"] },
      { group: "Drop", name: "Double drop D", notes: ["D2", "A2", "D3", "G3", "B3", "D4"] },
      { group: "Open", name: "Open D", notes: ["D2", "A2", "D3", "F#3", "A3", "D4"] },
      { group: "Open", name: "Open D minor", notes: ["D2", "A2", "D3", "F3", "A3", "D4"] },
      { group: "Open", name: "Open E", notes: ["E2", "B2", "E3", "G#3", "B3", "E4"] },
      { group: "Open", name: "Open G", notes: ["D2", "G2", "D3", "G3", "B3", "D4"] },
      { group: "Open", name: "Open G minor", notes: ["D2", "G2", "D3", "G3", "Bb3", "D4"] },
      { group: "Open", name: "Open A", notes: ["E2", "A2", "E3", "A3", "C#4", "E4"] },
      { group: "Open", name: "Open C", notes: ["C2", "G2", "C3", "G3", "C4", "E4"] },
      { group: "Open", name: "Open C6", notes: ["C2", "A2", "C3", "G3", "C4", "E4"] },
      { group: "Open", name: "Open F", notes: ["C2", "F2", "C3", "F3", "A3", "F4"] },
      { group: "Open", name: "Open B", notes: ["B1", "F#2", "B2", "F#3", "B3", "D#4"] },
      { group: "Modal & alternate", name: "DADGAD", notes: ["D2", "A2", "D3", "G3", "A3", "D4"] },
      { group: "Modal & alternate", name: "DADDAD", notes: ["D2", "A2", "D3", "D3", "A3", "D4"] },
      { group: "Modal & alternate", name: "CGCGCD", notes: ["C2", "G2", "C3", "G3", "C4", "D4"] },
      { group: "Modal & alternate", name: "All fourths", notes: ["E2", "A2", "D3", "G3", "C4", "F4"] },
      { group: "Modal & alternate", name: "Major thirds", notes: ["G#2", "C3", "E3", "G#3", "C4", "E4"] },
      { group: "Modal & alternate", name: "New standard (Fripp)", notes: ["C2", "G2", "D3", "A3", "E4", "G4"] },
      { group: "Modal & alternate", name: "Nashville (high strung)", notes: ["E3", "A3", "D4", "G4", "B3", "E4"] },
    ],
  },
  guitar7: {
    name: "Guitar (7-string)",
    strings: 7,
    tunings: [
      { name: "Standard", notes: ["B1", "E2", "A2", "D3", "G3", "B3", "E4"] },
      { name: "Half step down", notes: ["Bb1", "Eb2", "Ab2", "Db3", "Gb3", "Bb3", "Eb4"] },
      { name: "Drop A", notes: ["A1", "E2", "A2", "D3", "G3", "B3", "E4"] },
      { name: "A standard", notes: ["A1", "D2", "G2", "C3", "F3", "A3", "D4"] },
      { name: "Drop G", notes: ["G1", "D2", "G2", "C3", "F3", "A3", "D4"] },
    ],
  },
  guitar8: {
    name: "Guitar (8-string)",
    strings: 8,
    tunings: [
      { name: "Standard", notes: ["F#1", "B1", "E2", "A2", "D3", "G3", "B3", "E4"] },
      { name: "Drop E", notes: ["E1", "B1", "E2", "A2", "D3", "G3", "B3", "E4"] },
    ],
  },
  bass4: {
    name: "Bass (4-string)",
    strings: 4,
    tunings: [
      { name: "Standard", notes: ["E1", "A1", "D2", "G2"] },
      { name: "Half step down", notes: ["Eb1", "Ab1", "Db2", "Gb2"] },
      { name: "Drop D", notes: ["D1", "A1", "D2", "G2"] },
      { name: "D standard", notes: ["D1", "G1", "C2", "F2"] },
      { name: "Drop C", notes: ["C1", "G1", "C2", "F2"] },
      { name: "BEAD", notes: ["B0", "E1", "A1", "D2"] },
    ],
  },
  bass5: {
    name: "Bass (5-string)",
    strings: 5,
    tunings: [
      { name: "Standard (low B)", notes: ["B0", "E1", "A1", "D2", "G2"] },
      { name: "High C", notes: ["E1", "A1", "D2", "G2", "C3"] },
      { name: "Drop A", notes: ["A0", "E1", "A1", "D2", "G2"] },
    ],
  },
  bass6: {
    name: "Bass (6-string)",
    strings: 6,
    tunings: [{ name: "Standard", notes: ["B0", "E1", "A1", "D2", "G2", "C3"] }],
  },
  ukulele: {
    name: "Ukulele",
    strings: 4,
    tunings: [
      { name: "Standard (high G)", notes: ["G4", "C4", "E4", "A4"] },
      { name: "Low G", notes: ["G3", "C4", "E4", "A4"] },
      { name: "D tuning", notes: ["A4", "D4", "F#4", "B4"] },
      { name: "Baritone", notes: ["D3", "G3", "B3", "E4"] },
    ],
  },
  banjo: {
    name: "Banjo (5-string)",
    strings: 5,
    tunings: [
      { name: "Open G", notes: ["G4", "D3", "G3", "B3", "D4"] },
      { name: "Double C", notes: ["G4", "C3", "G3", "C4", "D4"] },
      { name: "Open D", notes: ["F#4", "D3", "F#3", "A3", "D4"] },
      { name: "G modal (sawmill)", notes: ["G4", "D3", "G3", "C4", "D4"] },
    ],
  },
  mandolin: {
    name: "Mandolin",
    strings: 4,
    tunings: [{ name: "Standard", notes: ["G3", "D4", "A4", "E5"] }],
  },
};
